GET http://localhost:3000/pets

###
GET  http://localhost:3000/pets/41

###
POST http://localhost:3000/pets
Content-Type: application/json

{
    "name": "Dog",      
    "especie": "passarinho", 
    "raca": "Canario",    
    "idade": 2           
}


###
PATCH http://localhost:3000/pets/41
Content-Type: application/json

{
  "name": "Pitocos2"
}


###
DELETE  http://localhost:3000/pets/3


###
//findOneVeterinarios
GET  http://localhost:3000/pets/41/veterinarios