GET http://localhost:3000/pets

###
GET  http://localhost:3000/pets/2

###
POST http://localhost:3000/pets
Content-Type: application/json

{
  "name": "Pitoco"
}

###
PATCH http://localhost:3000/pets/2
Content-Type: application/json

{
  "name": "Pitocos2"
}


###
DELETE  http://localhost:3000/pets/3