GET http://localhost:3000/consultas

###
GET  http://localhost:3000/consultas/1


###

POST http://localhost:3000/consultas
Content-Type: application/json

{
  "veterinarioIds": [4], 
  "petIds": [9], 
  "produtoIds": [3], 
  "observacoes": "Gengivite leve, prescrevi anti-inflamatório.",
  "dataConsulta": "2025-10-13"
}



###
PATCH http://localhost:3000/consultas/1
Content-Type: application/json

{
  "veterinarioIds": [5], 
  "petIds": [1], 
  "produtoIds": [4], 
  "observacoes": "Consulta alterada via PATCH",
  "dataConsulta": "2025-10-13T01:57:26.000Z"
}

###
DELETE  http://localhost:3000/consultas/40



