GET http://localhost:3000/tutor

###
GET  http://localhost:3000/tutor/1

###

GET  http://localhost:3000/tutor/1/pets

###
POST http://localhost:3000/tutor
Content-Type: application/json

{
  "name": "Ademir",
  "email": "email@email.com",
  "pets": [ 
    {
      "name": "Pitoco"
    },
    {
      "name": "Neguinho"
    }
  ]
}

###
PATCH http://localhost:3000/tutor/1
Content-Type: application/json

{
  "name": "Ademir 2",
  "email": "email@email.com",
  "pets": [ 
    {
      "name": "Pitocos2"
    },
    {
      "name": "Neguinhos2"
    }
  ]
}



###
DELETE  http://localhost:3000/tutor/1