GET http://localhost:3000/tutor

###
GET  http://localhost:3000/tutor/1

###
//findOneAnimal
GET  http://localhost:3000/tutor/1/pets


###
//findOneProduto
GET  http://localhost:3000/tutor/1/produtos

###
POST http://localhost:3000/tutor
Content-Type: application/json

{
  "name": "Tutor Name",
  "email": "email@example.com",
  "telefone": "123456789"
}

###
//addPetToExistingTutor
POST  http://localhost:3000/tutor/1/add-produtos
Content-Type: application/json

{
  "produtoIds": 4
}


###
PATCH http://localhost:3000/tutor/69
Content-Type: application/json

{
  "name": "Tutor Name",
  "email": "email@email.com",
  "telefone": "123456789"
}



###
//addPetToExistingTutor
PATCH http://localhost:3000/tutor/2/add-pet
Content-Type: application/json

{
  "petIds": 10
}


###
DELETE  http://localhost:3000/tutor/61


