GET http://localhost:3000/veterinario

###
GET  http://localhost:3000/veterinario/3

###
POST http://localhost:3000/veterinario
Content-Type: application/json

{
  "name": "Sebastião",
  "especialidade": "Cardiologia"
}

###
PATCH http://localhost:3000/veterinario/3
Content-Type: application/json

{
  "name": "jose 2"
}


###
DELETE  http://localhost:3000/veterinario/2




###
PATCH http://localhost:3000/veterinario/4/add-pet
Content-Type: application/json

{
  "petIds": 41
}


###
GET http://localhost:3000/veterinario/4/pets