GET http://localhost:3000/veterinario

###
GET  http://localhost:3000/veterinario/2

###
POST http://localhost:3000/veterinario
Content-Type: application/json

{
  "name": "Sebastião"
}

###
PATCH http://localhost:3000/veterinario/2
Content-Type: application/json

{
  "name": "jose 2"
}


###
DELETE  http://localhost:3000/veterinario/2