GET http://localhost:3000/produtos

###
GET  http://localhost:3000/produtos/10

###
POST http://localhost:3000/produtos
Content-Type: application/json

{
    "name": "Dipirorex",
    "categoria": "Medicamento",   
    "descricao": "Tomar 18 vezes ao dia"
}

###
PATCH http://localhost:3000/produtos/2
Content-Type: application/json

{
  "name": "osso"
}


###
DELETE  http://localhost:3000/produtos/2