GET http://localhost:3000/produtos

###
GET  http://localhost:3000/produtos/1

###
POST http://localhost:3000/produtos
Content-Type: application/json

{
  "name": "Bob Vendedor",
  "email": "bob@vendedor.com",
  "animals": [ 
    {
      "name": "Pingo"
    },
    {
      "name": "Lola"
    }
  ]
}

###
PATCH http://localhost:3000/produtos/1
Content-Type: application/json

{
  "name": "joão 4",
  "email": "email@email.com"
}


###
DELETE  http://localhost:3000/produtos/1